services:

    _defaults:
        autowire: true
        autoconfigure: true

    NetBS\CoreBundle\Form\FormErrorExtension:
#        arguments:
#            - "@session"
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    NetBS\CoreBundle\Form\Type\DatepickerType:
#        arguments:
#            - "@netbs.params"
        tags:
            - { name: form.type }

    NetBS\CoreBundle\Form\Type\SwitchType:
        tags:
            - { name: form.type }

    NetBS\CoreBundle\Form\Type\DateMaskType:
#        arguments:
#            - "@netbs.params"
        tags:
            - { name: form.type }

    NetBS\CoreBundle\Form\Type\QuillType:
        tags:
            - { name: form.type }

    NetBS\CoreBundle\Form\Type\TrumbowygType:
        tags:
            - { name: form.type }

    NetBS\CoreBundle\Form\Type\Select2DocumentType:
        tags:
            - { name: form.type }

    NetBS\CoreBundle\Form\Type\AjaxSelect2DocumentType:
#        arguments:
#            - "@doctrine.orm.entity_manager"
#            - "@netbs.core.select2_providers_manager"
        tags:
            - { name: form.type }
