
imports:
    - { resource: "voter.yml" }

services:

    netbs.secure.user_manager:
        class: NetBS\SecureBundle\Service\UserManager
        arguments:
            - "@security.password_encoder"
            - "@netbs.secure.config"
            - "@doctrine.orm.entity_manager"

    netbs.secure.config:
        class: NetBS\SecureBundle\Service\SecureConfig

    netbs.secure.list.users:
        class: NetBS\SecureBundle\ListModel\UsersList
        tags:
            - { name: netbs.list.model }

    netbs.secure.list.autorisations:
        class: NetBS\SecureBundle\ListModel\AutorisationsList
        tags:
        - { name: netbs.list.model }

    netbs.secure.extend_main_menu_listener:
        class: NetBS\SecureBundle\Listener\MainMenuListener
        arguments:
            - "@security.token_storage"
            - "@doctrine.orm.entity_manager"
            - "@netbs.secure.config"
        tags:
            - { name: kernel.event_listener, event: netbs.menu.extend, method: onMenuConfigure, priority: 60 }

    netbs.secure.listener.remove_membre:
        class: NetBS\SecureBundle\Listener\RemoveMembreListener
        arguments:
            - "@netbs.secure.config"
            - "@netbs.secure.user_manager"
        tags:
            - { name: kernel.event_listener, event: netbs.remove.membre, method: onRemove }

    netbs.secure.select2.roles_provider:
        class: NetBS\SecureBundle\Select2\RolesProvider
        tags:
            - { name: netbs.select2_provider }

    netbs.secure.select2.user_provider:
        class: NetBS\SecureBundle\Select2\UserProvider
        tags:
            - { name: netbs.select2_provider }

    netbs.secure.fichier.subscriber.doctrine_mapper:
        class: NetBS\SecureBundle\Subscriber\DoctrineMapperSubscriber
        arguments:
            - "@netbs.fichier.config"
            - "@netbs.secure.config"
        tags:
            - { name: doctrine.event_subscriber }

    netbs.secure.form.user:
        class: NetBS\SecureBundle\Form\UserType
        arguments:
            - "@netbs.fichier.config"
            - "@netbs.secure.config"
        tags:
            - { name: form.type }

    netbs.secure.form.autorisation:
        class: NetBS\SecureBundle\Form\AutorisationType
        arguments:
        - "@netbs.fichier.config"
        - "@netbs.secure.config"
        tags:
        - { name: form.type }

    netbs.secure.helper.user:
        class: NetBS\SecureBundle\Helper\UserHelper
        arguments:
            - "@netbs.secure.config"
        tags:
            - { name: netbs.helper }
