imports:
    - { resource: config.yml }

services:
    redis_cache_service:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            - method: setRedis
              arguments:
                - '@redis'
    redis:
        class: Redis
        calls:
            - { method: connect, arguments: ['%redis_host%', '%redis_port%'] }
            - { method: auth, arguments: ['%redis_pass%'] }
            - { method: select, arguments: ['%redis_db_index%'] }

            
doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: redis_cache_service
        result_cache_driver:
            type: service
            id: redis_cache_service
        query_cache_driver:
            type: service
            id: redis_cache_service


monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false


