tdgl:
    resource: "@TDGLBundle/Controller/"
    type:     annotation
    prefix:   /

netbs:
    resource: '@NetBSCoreBundle/Resources/config/routing.yml'
    prefix: /netBS

home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /netBS
        permanent: true
