<?php

namespace Ovesco\FacturationBundle\Repository;

/**
 * CreanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreanceRepository extends \Doctrine\ORM\EntityRepository
{
}
