<?php

namespace Ovesco\FacturationBundle\Repository;

/**
 * RappelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RappelRepository extends \Doctrine\ORM\EntityRepository
{
}
