services:

    _defaults:
        autowire: true
        autoconfigure: true

    NetBS\FichierBundle\Exporter\CSVMembre:
#        arguments:
#            - "@netbs.fichier.config"
        tags:
            - { name: netbs.exporter }

    NetBS\FichierBundle\Exporter\PDFEtiquettesV2:
        tags:
            - { name: netbs.exporter }

    NetBS\FichierBundle\Exporter\CSVRega:
#        arguments:
#            - "@netbs.fichier.config"
        tags:
            - { name: netbs.exporter }
