
services:

    _defaults:
        autowire: true
        autoconfigure: true

    NetBS\FichierBundle\LogRepresenter\MembreLogRepresenter:
        tags:
            - { name: netbs.log_representer }

    NetBS\FichierBundle\LogRepresenter\AttributionLogRepresenter:
        tags:
            - { name: netbs.log_representer }

    NetBS\FichierBundle\LogRepresenter\GroupeLogRepresenter:
        tags:
            - { name: netbs.log_representer }

    NetBS\FichierBundle\LogRepresenter\FamilleLogRepresenter:
        tags:
            - { name: netbs.log_representer }

    NetBS\FichierBundle\LogRepresenter\GeniteurLogRepresenter:
        tags:
            - { name: netbs.log_representer }

    NetBS\FichierBundle\LogRepresenter\ObtentionDistinctionLogRepresenter:
        tags:
            - { name: netbs.log_representer }

    NetBS\FichierBundle\LogRepresenter\AdresseLogRepresenter:
#        arguments:
#            - "@netbs.fichier.contact_manager"
        tags:
            - { name: netbs.log_representer }

    NetBS\FichierBundle\LogRepresenter\TelephoneLogRepresenter:
#        arguments:
#            - "@netbs.fichier.contact_manager"
        tags:
            - { name: netbs.log_representer }

    NetBS\FichierBundle\LogRepresenter\EmailLogRepresenter:
#        arguments:
#            - "@netbs.fichier.contact_manager"
        tags:
            - { name: netbs.log_representer }
