services:

    _defaults:
        autowire: true
        autoconfigure: true

    NetBS\FichierBundle\Voter\StructureVoter:
#        arguments:
#            - "@netbs.fichier.config"
        tags:
            - { name: security.voter }

    NetBS\FichierBundle\Voter\AttributionVoter:
#        arguments:
#            - "@netbs.fichier.config"
        tags:
            - { name: security.voter }

    NetBS\FichierBundle\Voter\ContactVoter:
#        arguments:
#            - "@netbs.fichier.config"
#            - "@netbs.fichier.contact_manager"
        tags:
            - { name: security.voter }

    NetBS\FichierBundle\Voter\GroupeVoter:
#        arguments:
#            - "@netbs.fichier.config"
        tags:
            - { name: security.voter }

    NetBS\FichierBundle\Voter\MembreFamilleVoter:
#        arguments:
#            - "@netbs.fichier.config"
        tags:
            - { name: security.voter }

    NetBS\FichierBundle\Voter\ObtentionDistinctionVoter:
#        arguments:
#            - "@netbs.fichier.config"
        tags:
            - { name: security.voter }
